### ISSUE TITLE
:crypto.hmac/3 is undefined or private

### ISSUE THREAD

**Issue by erwanvivien** [UNIRIS/uniris-node#32]
# Description

Running `iex -S mix phx.server` fails because of deprecated function in crypto library
 
# Expected Behaviour

Running node

# Actual Behaviour

```
warning: :crypto.hmac/3 is undefined or private. Did you mean one of:

      * mac/3
      * mac/4
      * macN/4
      * macN/5
 ```
 
# Steps To Reproduce

`iex -S mix phx.server`

# Platform 

Ubuntu 18.04 LTS

# Possible Solution

I tried replacing all hmac by mac (suggested by erlang), but I got an other error (full error: )

```
Generated uniris app
2021-05-18 14:27:13.705 [info] Try to open the port 3002
2021-05-18 14:27:13.707 [info] Port forwarding is skipped - reason: IP lookup provider is not NAT
2021-05-18 14:27:13.707 [info] Port must be open manually
2021-05-18 14:27:13.716 [info] Initialize InMemory Chain Lookup...
2021-05-18 14:27:13.717 [info] Initialize InMemory Pending Ledger...
2021-05-18 14:27:13.717 [info] Initialize InMemory KO Ledger...
2021-05-18 14:27:13.739 [error] GenServer Uniris.Crypto.SoftwareKeystore terminating
** (FunctionClauseError) no function clause matching in :crypto.mac/3
    (crypto 5.0) crypto.erl:588: :crypto.mac(:sha512, "", "node1")
    (uniris 0.10.0) lib/uniris/crypto.ex:238: Uniris.Crypto.get_extended_seed/2
    (uniris 0.10.0) lib/uniris/crypto.ex:114: Uniris.Crypto.derive_keypair/3
    (uniris 0.10.0) lib/uniris/crypto/keystore/software_impl.ex:66: Uniris.Crypto.SoftwareKeystore.handle_call/3
    (stdlib 3.15) gen_server.erl:721: :gen_server.try_handle_call/4
    (stdlib 3.15) gen_server.erl:750: :gen_server.handle_msg/6
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from Uniris.Crypto.KeystoreLoader): {:node_public_key, 0}
State: %{node_key_counter: 0, node_seed: "node1", node_shared_key_counter: 0}
Client Uniris.Crypto.KeystoreLoader is alive

    (stdlib 3.15) gen.erl:233: :gen.do_call/4
    (elixir 1.11.2) lib/gen_server.ex:1024: GenServer.call/3
    (uniris 0.10.0) lib/uniris/crypto/keystore/loader.ex:21: Uniris.Crypto.KeystoreLoader.init/1
    (stdlib 3.15) gen_server.erl:423: :gen_server.init_it/2
    (stdlib 3.15) gen_server.erl:390: :gen_server.init_it/6
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2021-05-18 14:27:13.764 [info] Application uniris exited: Uniris.Application.start(:normal, []) returned an error: shutdown: failed to start child: Uniris.Crypto.Supervisor
    ** (EXIT) shutdown: failed to start child: Uniris.Crypto.KeystoreLoader
        ** (EXIT) exited in: GenServer.call(Uniris.Crypto.SoftwareKeystore, {:node_public_key, 0}, 5000)
            ** (EXIT) an exception was raised:
                ** (FunctionClauseError) no function clause matching in :crypto.mac/3
                    (crypto 5.0) crypto.erl:588: :crypto.mac(:sha512, "", "node1")
                    (uniris 0.10.0) lib/uniris/crypto.ex:238: Uniris.Crypto.get_extended_seed/2
                    (uniris 0.10.0) lib/uniris/crypto.ex:114: Uniris.Crypto.derive_keypair/3
                    (uniris 0.10.0) lib/uniris/crypto/keystore/software_impl.ex:66: Uniris.Crypto.SoftwareKeystore.handle_call/3
                    (stdlib 3.15) gen_server.erl:721: :gen_server.try_handle_call/4
                    (stdlib 3.15) gen_server.erl:750: :gen_server.handle_msg/6
                    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application uniris: Uniris.Application.start(:normal, []) returned an error: shutdown: failed to start child: Uniris.Crypto.Supervisor
    ** (EXIT) shutdown: failed to start child: Uniris.Crypto.KeystoreLoader
        ** (EXIT) exited in: GenServer.call(Uniris.Crypto.SoftwareKeystore, {:node_public_key, 0}, 5000)
            ** (EXIT) an exception was raised:
                ** (FunctionClauseError) no function clause matching in :crypto.mac/3
                    (crypto 5.0) crypto.erl:588: :crypto.mac(:sha512, "", "node1")
                    (uniris 0.10.0) lib/uniris/crypto.ex:238: Uniris.Crypto.get_extended_seed/2
                    (uniris 0.10.0) lib/uniris/crypto.ex:114: Uniris.Crypto.derive_keypair/3
                    (uniris 0.10.0) lib/uniris/crypto/keystore/software_impl.ex:66: Uniris.Crypto.SoftwareKeystore.handle_call/3
                    (stdlib 3.15) gen_server.erl:721: :gen_server.try_handle_call/4
                    (stdlib 3.15) gen_server.erl:750: :gen_server.handle_msg/6
                    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
```

# Thanks for the help

**Comment by samuel-uniris** [comment]
Which version of Elixir/OTP are you using ?

**Comment by erwanvivien** [comment]
Elixir 1.11.*
Elixir/OTP 24

if that helps

**Comment by roychowdhuryrohit-dev** [comment]
> Elixir 1.11.*
> Elixir/OTP 24
> 
> if that helps

Can you try upgrading erlang and openssl?

**Comment by samuel-uniris** [comment]
OTP24 does not support indeed :crypto.hmac function anymore.
A fix is coming, but as in README.md, we supported OTP23.

**Comment by erwanvivien** [comment]
Ok, thanks a lot, i'll close the issue
